## 1. IMPORT LIBRARIES

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

## 2. LOADING  DATA

In [5]:
customers=pd.read_csv("olist_customers_dataset.csv")
order_items=pd.read_csv("olist_order_items_dataset.csv")
orders=pd.read_csv("olist_orders_dataset.csv")
products=pd.read_csv("olist_products_dataset.csv")

In [6]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

## 3. INSPECTING Data

In [7]:
customers.shape

(99441, 5)

In [8]:
orders.shape

(99441, 8)

In [9]:
order_items.shape

(112650, 7)

In [10]:
products.shape

(32951, 9)

In [11]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

In [12]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [13]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')

In [14]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

In [15]:
customers.dtypes

customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

In [16]:
orders.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [17]:
order_items.dtypes

order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

In [18]:
products.dtypes

product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

## 4. DATA Quality

In [19]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [20]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [21]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [22]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [23]:
customers.duplicated().sum()

np.int64(0)

In [24]:
orders.duplicated().sum()

np.int64(0)

In [25]:
order_items.duplicated().sum()

np.int64(0)

In [26]:
products.duplicated().sum()

np.int64(0)

In [27]:
customers.describe()

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [28]:
order_items.describe()

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [29]:
orders.describe()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-03-31 15:08:21,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

In [30]:
products.describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

## 5.Relationships

In [31]:
orders["customer_id"].isin(customers["customer_id"]).sum()

np.int64(99441)

In [32]:
order_items["order_id"].isin(orders["order_id"]).sum()

np.int64(112650)

In [33]:
order_items["product_id"].isin(products["product_id"]).sum()

np.int64(112650)

## 5.CLEANING and Handling missing values

In [34]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [35]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [36]:
orders[orders["order_delivered_customer_date"].isnull()]["order_status"].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [37]:
orders[
    (orders["order_delivered_customer_date"].isnull()) &
    (orders["order_status"] == "delivered")
][[
    "order_id",
    "order_status",
    "order_purchase_timestamp",
    "order_delivered_carrier_date",
    "order_estimated_delivery_date"
]]

,order_id,order_status,order_purchase_timestamp,order_delivered_carrier_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,delivered,2017-11-28 17:44:07,2017-11-30 18:12:23,2017-12-18 00:00:00
20618,f5dd62b788049ad9fc0526e3ad11a097,delivered,2018-06-20 06:58:43,2018-06-25 08:05:00,2018-07-16 00:00:00
43834,2ebdfc4f15f23b91474edf87475f108e,delivered,2018-07-01 17:05:11,2018-07-03 13:57:00,2018-07-30 00:00:00
79263,e69f75a717d64fc5ecdfae42b2e8e086,delivered,2018-07-01 22:05:55,2018-07-03 13:57:00,2018-07-30 00:00:00
82868,0d3268bad9b086af767785e3f0fc0133,delivered,2018-07-01 21:14:02,2018-07-03 09:28:00,2018-07-24 00:00:00
92643,2d858f451373b04fb5c984a1cc2defaf,delivered,2017-05-25 23:22:43,NaN,2017-06-23 00:00:00
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,delivered,2018-06-08 12:09:39,2018-06-12 14:10:00,2018-06-26 00:00:00
98038,20edc82cf5400ce95e1afacc25798b31,delivered,2018-06-27 16:09:12,2018-07-03 19:26:00,2018-07-19 00:00:00

In [38]:
orders[orders["order_approved_at"].isnull()]["order_status"].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [39]:
orders[orders["order_delivered_carrier_date"].isnull()]["order_status"].value_counts()

order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

In [40]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [41]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [42]:
products[
    (products["product_category_name"].isnull()) 
][[
    "product_id",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]]

,product_id,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,300.0,35.0,7.0,12.0
...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,700.0,28.0,3.0,43.0

In [43]:
products["product_category_name"] = products["product_category_name"].fillna("Unknown")

In [44]:
products["product_category_name"].isnull().sum()

np.int64(0)

In [45]:
customers.duplicated().sum()

np.int64(0)

In [46]:
orders.duplicated().sum()

np.int64(0)

In [47]:
order_items.duplicated().sum()

np.int64(0)

In [48]:
products.duplicated().sum()

np.int64(0)

## 6.Transformation

In [49]:
sales=order_items[["order_id","product_id","price","freight_value"]].merge(
    orders[["order_id","customer_id","order_purchase_timestamp","order_status"]],
    on="order_id")

In [50]:
sales.shape

(112650, 7)

In [51]:
sales=sales.merge(
    products[["product_id","product_category_name"]],
    on="product_id"
)

In [52]:
sales.shape

(112650, 8)

In [53]:
sales["sales_amount"]=sales["price"]+sales["freight_value"]

In [54]:
sales.shape

(112650, 9)

## Date transformation

In [55]:
sales["order_purchase_timestamp"]=pd.to_datetime(sales["order_purchase_timestamp"])

In [56]:
sales["year"]=sales["order_purchase_timestamp"].dt.year
sales["month"]=sales["order_purchase_timestamp"].dt.month

In [57]:
sales.shape

(112650, 11)

## 7. Create dimension tables

In [58]:
dim_date=sales["order_purchase_timestamp"].dt.date

In [59]:
dim_date = pd.DataFrame({
    "date":sales["order_purchase_timestamp"].dt.date,
    "year":sales["order_purchase_timestamp"].dt.year,
    "month":sales["order_purchase_timestamp"].dt.month
})

In [60]:
dim_date

              date  year  month
0       2017-09-13  2017      9
1       2017-04-26  2017      4
2       2018-01-14  2018      1
3       2018-08-08  2018      8
4       2017-02-04  2017      2
...            ...   ...    ...
112645  2018-04-23  2018      4
112646  2018-07-14  2018      7
112647  2017-10-23  2017     10
112648  2017-08-14  2017      8
112649  2018-06-09  2018      6

[112650 rows x 3 columns]

In [61]:
dim_customer=pd.DataFrame({
    "customer_id":customers["customer_id"],
    "customer_unique_id":customers["customer_unique_id"],
    "customer_zip_code_prefix":customers["customer_zip_code_prefix"],
    "customer_city":customers["customer_city"],
    "customer_state":customers["customer_state"],
})

In [62]:
dim_customer.shape

(99441, 5)

In [63]:
dim_product=pd.DataFrame({
    "product_id":products["product_id"],
    "product_category_name":products["product_category_name"]
})

In [64]:
dim_product.shape

(32951, 2)

In [65]:
fact_sales=pd.DataFrame({
    "order_id":sales["order_id"],
    "product_id":sales["product_id"],
    "customer_id":sales["customer_id"],
    "order_purchase_timestamp":sales["order_purchase_timestamp"],
    "product_category_name":sales["product_category_name"],
    "price":sales["price"],
    "freight_value":sales["freight_value"],
    "sales_amount":sales["sales_amount"],
    "year":sales["year"],
    "month":sales["month"]
})

In [66]:
fact_sales.shape

(112650, 10)

## 8.Validate Tables

In [74]:
dim_date=dim_date.drop_duplicates("date")

In [75]:
dim_date.shape

(616, 3)

In [68]:
dim_product.shape

(32951, 2)

In [69]:
dim_customer.shape

(99441, 5)

In [70]:
fact_sales.shape

(112650, 10)

In [76]:
fact_sales.isnull().sum()

order_id                    0
product_id                  0
customer_id                 0
order_purchase_timestamp    0
product_category_name       0
price                       0
freight_value               0
sales_amount                0
year                        0
month                       0
dtype: int64

In [77]:
fact_sales.duplicated().sum()

np.int64(10225)

In [78]:
fact_sales.duplicated(subset=["order_id", "product_id"]).sum()

np.int64(10225)

In [79]:
fact_sales.duplicated(
    subset=["order_id", "product_id", "price", "freight_value"]
).sum()

np.int64(10225)

In [80]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')

In [81]:
order_items.duplicated(subset=["order_id", "order_item_id"]).sum()

np.int64(0)

In [82]:
fact_sales["price"]+fact_sales["freight_value"]==fact_sales["sales_amount"]

0         True
1         True
2         True
3         True
4         True
          ...
112645    True
112646    True
112647    True
112648    True
112649    True
Length: 112650, dtype: bool

## Validate relationships

In [83]:
fact_sales["customer_id"].isin(dim_customer["customer_id"]).sum()

np.int64(112650)

In [84]:
fact_sales["product_id"].isin(dim_product["product_id"]).sum()

np.int64(112650)

## validate total sales

In [85]:
fact_sales["sales_amount"].sum()

np.float64(15843553.24)

## 8.Load tables into MYSQL

In [88]:
import sqlalchemy

In [93]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:78655@localhost:3306/olist_bi"
)

In [94]:
dim_customer.to_sql(
    "dim_customer",
    con=engine,
    if_exists="replace",
    index=False
)

99441

In [95]:
dim_product.to_sql(
    "dim_product",
    con=engine,
    if_exists="replace",
    index=False
)

32951

In [96]:
dim_date.to_sql(
    "dim_date",
    con=engine,
    if_exists="replace",
    index=False
)

616

In [97]:
fact_sales.to_sql(
    "fact_sales",
    con=engine,
    if_exists="replace",
    index=False
)

112650